blank_issues_enabled: true
contact_links:
  - name: ğŸ’¬ Questions & Discussions ğŸ’¬
    url: https://github.com/vladelaina/Catime/discussions
    about: "ğŸ¤ Use GitHub discussions for message-board style questions and discussions."

